In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('rawdata.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4025 entries, 0 to 4024
Data columns (total 57 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            4025 non-null   int64
 1   age                   4025 non-null   float64
 2   gender                4025 non-null   float64
 3   x                     4025 non-null   float64
 4   y                     4025 non-null   float64
 5   w                     4025 non-null   float64
 6   h                     4025 non-null   float64
 7   yaw                   4025 non-null   float64
 8   pitch                 4025 non-null   float64
 9   roll                  4025 non-null   float64
 10  score                 4025 non-null   float64
 11  left_eyebrow_x_mean   4025 non-null   float64
 12  left_eyebrow_y_mean   4025 non-null   float64
 13  left_eyebrow_x_min    4025 non-null   float64
 14  left_eyebrow_x_max    4025 non-null   float64
 15  left_eyebrow_y_min    4025 non-null   float64
 16  left_eyebrow_y_max    4025 non-null   float64
 17  jaw_x_mean            4025 non-null   float64
 18  jaw_y_mean            4025 non-null   float64
 19  jaw_x_min             4025 non-null   float64
 20  jaw_x_max             4025 non-null   float64
 21  jaw_y_min             4025 non-null   float64
 22  jaw_y_max             4025 non-null   float64
 23  left_eye_x_mean       4025 non-null   float64
 24  left_eye_y_mean       4025 non-null   float64
 25  left_eye_x_min        4025 non-null   float64
 26  left_eye_x_max        4025 non-null   float64
 27  left_eye_y_min        4025 non-null   float64
 28  left_eye_y_max        4025 non-null   float64
 29  lip_x_mean            4025 non-null   float64
 30  lip_y_mean            4025 non-null   float64
 31  lip_x_min             4025 non-null   float64
 32  lip_x_max             4025 non-null   float64
 33  lip_y_min             4025 non-null   float64
 34  lip_y_max             4025 non-null   float64
 35  nose_x_mean           4025 non-null   float64
 36  nose_y_mean           4025 non-null   float64
 37  nose_x_min            4025 non-null   float64
 38  nose_x_max            4025 non-null   float64
 39  nose_y_min            4025 non-null   float64
 40  nose_y_max            4025 non-null   float64
 41  right_eye_x_mean      4025 non-null   float64
 42  right_eye_y_mean      4025 non-null   float64
 43  right_eye_x_min       4025 non-null   float64
 44  right_eye_x_max       4025 non-null   float64
 45  right_eye_y_min       4025 non-null   float64
 46  right_eye_y_max       4025 non-null   float64
 47  right_eyebrow_x_mean  4025 non-null   float64
 48  right_eyebrow_y_mean  4025 non-null   float64
 49  right_eyebrow_x_min   4025 non-null   float64
 50  right_eyebrow_x_max   4025 non-null   float64
 51  right_eyebrow_y_min   4025 non-null   float64
 52  right_eyebrow_y_max   4025 non-null   float64
 53  identification        4025 non-null   object
 54  rid                   4025 non-null   object
 55  width                 4025 non-null   int64
 56  height                4025 non-null   int64
dtypes: float64(52), int64(3), object(2)
memory usage: 1.8+ MB

In [4]:
data['score'].mean()

0.9388543749003677

In [5]:
data['score'].min()

0.7001731395721436

In [6]:
data.isnull()

,Unnamed: 0,age,gender,x,y,w,h,yaw,pitch,roll,...,right_eyebrow_x_mean,right_eyebrow_y_mean,right_eyebrow_x_min,right_eyebrow_x_max,right_eyebrow_y_min,right_eyebrow_y_max,identification,rid,width,height
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4020,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4021,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4022,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4023,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4024,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
data.duplicated().sum()

0

In [8]:
tmp = data['score'] < 0.8

In [9]:
tmp.sum()

363

In [10]:
sort_rawdata = data['score'] >= 0.85

In [11]:
sort_rawdata.sum()

3430

In [19]:
rawdata2 = data[sort_rawdata]

In [20]:
rawdata2.head()

,Unnamed: 0,age,gender,x,y,w,h,yaw,pitch,roll,...,right_eyebrow_x_mean,right_eyebrow_y_mean,right_eyebrow_x_min,right_eyebrow_x_max,right_eyebrow_y_min,right_eyebrow_y_max,identification,rid,width,height
0,0,25.829796,0.000568,0.438426,0.175270,0.090580,0.117666,0.076935,-0.067258,-0.016447,...,0.462462,0.203959,0.453371,0.472479,0.201499,0.207891,PS0100100101100356900000,a2509f1bbeb04335152a357eef593713,669,515
1,1,19.629601,0.232329,0.497499,0.227916,0.071276,0.100140,-0.578735,-0.135969,0.044935,...,0.520273,0.234467,0.511203,0.529914,0.231942,0.237303,PS0100100101100738000000,8446173f9647b9ff44d8375f176732ba,340,242
2,2,58.378593,0.838139,0.473221,0.479157,0.071485,0.047657,-0.275828,0.154273,0.240863,...,0.502881,0.491112,0.495392,0.511432,0.489564,0.494224,PS0100100100900254400000,3cd4d8459806093cf496a38f10b5fb27,2000,3000
3,3,43.825607,0.263087,0.574504,0.584199,0.023727,0.024253,0.074296,-0.076718,0.018937,...,0.582349,0.588878,0.579690,0.585192,0.588355,0.589661,PS0100100100100650400007,d01d11b4318b75f0de92c23d2159bc87,3000,2935
4,4,40.084435,0.389530,0.618664,0.650157,0.017221,0.017603,0.086755,-0.136211,-0.017764,...,0.623908,0.655813,0.622283,0.625736,0.655477,0.656395,PS0100100100100650400007,d01d11b4318b75f0de92c23d2159bc87,3000,2935

In [22]:
del rawdata2['Unnamed: 0']

In [23]:
rawdata2.to_csv('rawdata_sort.csv')